spring:
  application:
    name: demo
nacos:
  server-addr: 192.168.187.128:8848
  context-path: /nacos
  namespace: ""
  username: nacos
  password: nacos
  config:
    enabled: true
    data-id: ${spring.application.name}.yml
    group: DEFAULT_GROUP
    type: yaml
    timeout: 3000
    http-only: true
    http-refresh-interval: 5000
  discovery:
    enabled: true
    group: DEFAULT_GROUP
    cluster-name: DEFAULT
    ephemeral: true
    weight: 1.0
